In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('bbc-text.csv')

In [17]:
data.head(10)

category                                               text
0         4  tv futur hand viewer home theatr system plasma...
1         0  worldcom boss left book alon former worldcom b...
2         3  tiger wari farrel gambl leicest say rush make ...
3         3  yead face newcastl fa cup premiership side new...
4         1  ocean twelv raid box offic ocean twelv crime c...
5         2  howard hit back mongrel jibe michael howard ha...
6         2  blair prepar name poll date toni blair like na...
7         3  henman hope end dubai third seed tim henman sl...
8         3  wilkinson fit face edinburgh england captain j...
9         1  last star war children sixth final star war mo...

In [4]:
data.describe()

category                                               text
count      2225                                               2225
unique        5                                               2126
top       sport  jobs growth still slow in the us the us create...
freq        511                                                  2

In [5]:
import nltk
nltk.download('stopwords')   # get NLTK library
nltk.download('punkt')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [6]:
from nltk.tokenize import word_tokenize 
from nltk.stem import PorterStemmer 
from nltk.corpus import stopwords
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

In [9]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [10]:
kalimat = 'he want to kiss his girlfriend'
kalimat = word_tokenize(kalimat)
print(kalimat)
for kata in kalimat:
    if kata not in stop_words:
        print(kata)

['he', 'want', 'to', 'kiss', 'his', 'girlfriend']
want
kiss
girlfriend


In [14]:
for i in range(len(data['text'])):  #perulangan sebanyak text
    new_article = ''   #membuat template artikel baru 
    article = word_tokenize(data['text'][i])   #potong artikel menjadi per-kata
    for word in article : #perulangan untuk setiap kaya
        word = word.lower()  #jadikan huruf kecil
        word = ps.stem(word) #ngebalikin ke kata dasar
        if word not in stop_words and len(word)>1 and word.isalpha():  #menghapus stopwords
            new_article = new_article + word + ' '
    data['text'][i] = new_article

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

kelas = list(data['category'].unique())   #me-list text nya

le.fit(kelas)    #ngasih pelabelan 
data['category'] = le.transform(data['category'])  #merubah menjadi angka

In [47]:
from sklearn.model_selection import train_test_split #memotong data text dan kategori tadi
#x : data, y :kelas
X_train, X_test, y_train, y_test = train_test_split(matriks_vector, data['category'], test_size=0.33, random_state=7)

In [28]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()  #ngitung jumlah kata - kata yg muncul dalam suatu artikel

In [38]:
matriks_vector = vectorizer.fit_transform(data['text'])
print(matriks_vector.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [30]:
vectorizer.get_feature_names() #ngelihat colomn katanya

['aa',
 'aaa',
 'aac',
 'aadc',
 'aaltra',
 'aan',
 'aarhu',
 'aaron',
 'abacu',
 'abandon',
 'abat',
 'abba',
 'abbasi',
 'abbey',
 'abbott',
 'abbrevi',
 'abc',
 'abd',
 'abdellatif',
 'abdic',
 'abdomen',
 'abdomin',
 'abdul',
 'abdullah',
 'abeb',
 'abensur',
 'aberdeen',
 'aberr',
 'abey',
 'abeyi',
 'abhorr',
 'abid',
 'abigail',
 'abil',
 'abiyot',
 'abl',
 'abn',
 'abnorm',
 'abolish',
 'abolit',
 'abort',
 'abortionist',
 'abov',
 'abraham',
 'abramovich',
 'abroad',
 'abruptli',
 'absa',
 'absenc',
 'absent',
 'absolut',
 'absorb',
 'abstain',
 'abstent',
 'absurd',
 'abtahi',
 'abu',
 'abund',
 'aburiz',
 'abut',
 'abuzz',
 'abysm',
 'ac',
 'academ',
 'academi',
 'acapulco',
 'acc',
 'accel',
 'accent',
 'accept',
 'access',
 'accessori',
 'accid',
 'acclaim',
 'acclim',
 'acclimati',
 'accolad',
 'accommod',
 'accomod',
 'accompani',
 'accompl',
 'accomplish',
 'accord',
 'accordingli',
 'account',
 'accoust',
 'accra',
 'accret',
 'accu',
 'accumul',
 'accur',
 'accuraci',

In [35]:
matriks_vector_test = vectorizer.fit_transform(X_test)
print(matriks_vector_test.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [43]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train.toarray(), y_train)  # Naive bayes belajar, dari data x_train, jawabannya categori y_train

GaussianNB(priors=None, var_smoothing=1e-09)

In [45]:
clf.predict(X_test.toarray())

array([2, 3, 3, 3, 1, 3, 3, 4, 3, 2, 3, 4, 3, 3, 4, 1, 4, 2, 4, 1, 0, 0,
       3, 4, 2, 3, 4, 0, 3, 4, 3, 0, 3, 1, 0, 1, 3, 0, 0, 2, 3, 0, 1, 1,
       3, 2, 4, 4, 4, 4, 3, 3, 3, 1, 3, 3, 0, 2, 1, 0, 2, 0, 0, 3, 2, 3,
       3, 0, 4, 2, 2, 3, 0, 2, 0, 4, 4, 1, 3, 2, 3, 3, 2, 2, 2, 3, 2, 1,
       2, 2, 1, 1, 4, 2, 3, 2, 1, 0, 4, 1, 1, 2, 4, 2, 2, 1, 1, 4, 2, 0,
       3, 1, 3, 2, 4, 3, 2, 2, 3, 3, 3, 4, 1, 0, 0, 0, 0, 1, 4, 3, 2, 1,
       0, 1, 4, 1, 2, 0, 2, 1, 3, 0, 3, 0, 0, 3, 0, 3, 0, 4, 1, 4, 0, 1,
       0, 2, 3, 2, 0, 2, 0, 2, 3, 3, 2, 2, 0, 3, 4, 4, 2, 0, 0, 1, 0, 3,
       2, 1, 3, 4, 2, 2, 1, 1, 3, 0, 1, 3, 0, 0, 4, 2, 4, 2, 3, 2, 0, 3,
       0, 0, 2, 0, 2, 2, 2, 0, 4, 3, 4, 3, 0, 3, 4, 1, 2, 0, 1, 0, 1, 0,
       4, 0, 2, 1, 1, 1, 3, 3, 0, 1, 3, 4, 0, 4, 3, 1, 3, 2, 4, 3, 1, 2,
       4, 3, 3, 1, 2, 1, 1, 0, 3, 1, 4, 2, 4, 2, 1, 4, 1, 4, 0, 1, 3, 4,
       2, 0, 0, 0, 2, 2, 0, 1, 2, 2, 0, 3, 2, 2, 4, 0, 4, 2, 2, 4, 0, 3,
       2, 1, 0, 0, 3, 0, 4, 3, 0, 1, 1, 2, 4, 2, 3,

In [48]:
clf.score(X_test.toarray(),y_test) * 100

96.87074829931973